version: "3.9"

services:

  php:
    build: ./docker/php
    volumes:
      - ./back:/var/www/html/back
      - ./front:/var/www/html/front
    container_name: tracker-php

  nginx:
    image: nginx:alpine
    container_name: tracker-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./back:/var/www/html/back
      - ./front:/var/www/html/front
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: tracker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
